### ISSUE TITLE
Vault Group in chat

### ISSUE THREAD

**Issue by Synapz1** [Synapz1/Paintball#24]
Have vault hook into chat to show prefix/group name

**Comment by Fridgey** [comment]
vault..?

**Comment by Synapz1** [comment]
Yes Vault

**Comment by Fridgey** [comment]
What does vault have to do with group names? I've never used vault. I've always used  pex or group manager to hook into for prefixes.

**Comment by Dart2112** [comment]
PEX and that store group prefixes in vault for plugins to use. That's my understanding

**Comment by Synapz1** [comment]
Yes what dart said. Those other chat plugins (PEX, GroupManager, Essentials Chat, etc) each hook into Vault. Check setupEconomy in Paintball class. (I have to rename it to be a little more abstract) but there is a Chat class to get the prefix, suffix, etc. This way I do not have to hook into every single chat plugin and just Vault.

**Comment by Fridgey** [comment]
Oh :o i never knew that. awesome
