### ISSUE TITLE
Duplicated leaderboard entries

### ISSUE THREAD

**Issue by Synapz1** [Synapz1/Paintball#25]
On /pb top <stat> there are sometimes many duplicate entries

**Comment by Fridgey** [comment]
It's because players sometimes have the same score. So say if 4 players have the same score, rn you grab the player at index 0, and display it 4 times. Now you know why it doesn't work now fix it :D

**Comment by Fridgey** [comment]
Check the changes in latest commit. If okay, then close this, if not reply with why not.
