### ISSUE TITLE
Use a connection pool for mysql usage.

### ISSUE THREAD

**Issue by Fridgey** [Synapz1/Paintball#29]

**Comment by Fridgey** [comment]
Can we remove sqlite? Nobody uses it.

**Comment by Synapz1** [comment]
Sure

**Comment by Synapz1** [comment]
So this is finished right?

We need to configure the pom.xml to build with the MySQL file you are using now.

**Comment by Fridgey** [comment]
It's already been ready for such a long time(the pom.xml)

**Comment by Synapz1** [comment]
No it does not build with it when you compile with the maven plugin. It needs to be shaded in.

**Comment by Synapz1** [comment]
Are you able to build it with MySQL working? I talked with some people and they said that the only way to build it was with the Maven plugin that comes in IntelliJ. I tried your way but they said that will not work.

**Comment by Synapz1** [comment]
I got it to work.

MySQL needs testing though.
