### ISSUE TITLE
NPE when editing arena

### ISSUE THREAD

**Issue by SimSonic** [Synapz1/Paintball#30]
I'm trying to setup arena from scratch but there is an NPE when executing /pb arena ArenaName setteams &4,&9 (or any set spawn / lobby, and on /pb admin reload too).

![image](https://cloud.githubusercontent.com/assets/2697754/17660346/0411a024-6303-11e6-828e-0f7f71026a1d.png)

**Comment by Synapz1** [comment]
Delete arenas.yml file and try

**Comment by SimSonic** [comment]
It was absent when I start. Deleted many times.
My fix look like this:
https://github.com/Synapz1/Paintball/blob/master/src/me/synapz/paintball/enums/Team.java#L127
change **return color;** to **return color != null ? color : ChatColor.ITALIC;**

**Comment by Synapz1** [comment]
I think I see it now. What you said is just like a quick fix. When you typed the command In you did not specify the arena. There should be an error to catch that issue. I will test & add that if that is why it has that error

**Comment by SimSonic** [comment]
> When you typed the command In you did not specify the arena.
I've entered /pb arena ArenaName setteams &4,&9 but github hided arenaname in brackets =)

Thanks.

**Comment by Synapz1** [comment]
It is /pb areana setteams arena teams

**Comment by SimSonic** [comment]
Oh, the arguments in different commands have too chaotic order. I think you have to review them.

**Comment by Synapz1** [comment]
What? How are they in too chaotic order? They are all organized. Every single command is /pb admin/arena <arena> <additional parameters>. No command in there is /pb admin/arena <arena>. Don't see how it is too chaotic at all; all commands follow a specific pattern throughout. 

And it is working fine for me everything I try with no errors. Can you show me arenas.yml, what you typed in when you created an arena, and the stacktrace? Maybe the IP too if you want me to try and join.

**Comment by SimSonic** [comment]
It had such nodes:
> &4: null
> &9: null

I can't show it now cause I've rebuild jar with fix I show above. All become working.

**Comment by Synapz1** [comment]
So you fixed it and it works fine?

**Comment by SimSonic** [comment]
Yep.
